name: 'action-invitations-report'
description: 'Create a report of organization invites'

inputs:
  token:
    description: 'A Personal Access token with admin:org, read:user, repo, user:email scopes'
    required: true
  report-path:
    description: 'Path to the report file'
    default: 'invitation-report.csv'
    required: false
  enterprise:
    description: 'GitHub Enterprise Cloud account, will require the token to have admin:org, read:enterprise, read:user, repo, user:email scopes'
    required: false
  committer-name:
    description: 'The name of the committer that will appear in the Git history'
    default: 'invitation-reporter[bot]'
    required: false
  committer-email:
    description: 'The committer email that will appear in the Git history'
    default: 'invitation@reporter'
    required: false

outputs:
  base-sha:
    description: 'Report base SHA'
  head-sha:
    description: 'Report head SHA'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: file-text
  color: green
